package com.cadebray.healthmanager;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "health_logs")
public class Log {
    @PrimaryKey(autoGenerate = true)
    private long id;
    private String date;
    private String time;
    private float weight;
    private String weightUnit;
    private String username;

    // Constructors, getters, and setters. Putting suppressions for unused warnings to better utilize
    // the IDE problems debugging.

    public Log() {
        // Default constructor
        this.date = "";
        this.time = "";
        this.weight = 0.0f;
        this.weightUnit = "";
        this.username = "";
    }

    /**
     * Getter for the id. This is the primary key.
     * @return The id of the log.
     */
    public long getId() {
        return id;
    }

    /**
     * This is the only setter that is private. It shouldn't be used outside of the class because
     * the id is auto-generated by Room.
     * @param id The id to set as an int. This will be the primary key.
     */
    @SuppressWarnings("unused")
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Getter for the date.
     * @return The date of the log as a string.
     */
    @SuppressWarnings("unused")
    public String getDate() {
        return date;
    }

    /**
     * Setter for the date.
     * @param date The date to set as a string.
     */
    @SuppressWarnings("unused")
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Getter for the time.
     * @return The time of the log as a string.
     */
    @SuppressWarnings("unused")
    public String getTime() {
        return time;
    }

    /**
     * Setter for the time.
     * @param time The time to set as a string.
     */
    @SuppressWarnings("unused")
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * Getter for the weight.
     * @return The weight of the log as a float.
     */
    @SuppressWarnings("unused")
    public float getWeight() {
        return weight;
    }

    /**
     * Setter for the weight.
     * @param weight The weight to set as a float.
     */
    @SuppressWarnings("unused")
    public void setWeight(float weight) {
        this.weight = weight;
    }

    /**
     * Getter for the weight unit.
     * @return The weight unit of the log as a string.
     */
    @SuppressWarnings("unused")
    public String getWeightUnit() {
        return weightUnit;
    }

    /**
     * Setter for the weight unit.
     * @param weightUnit The weight unit to set as a string.
     */
    @SuppressWarnings("unused")
    public void setWeightUnit(String weightUnit) {
        this.weightUnit = weightUnit;
    }

    /**
     * Getter for the username.
     * @return The username of the log as a string.
     */
    @SuppressWarnings("unused")
    public String getUsername() {
        return username;
    }

    /**
     * Setter for the username.
     * @param username The username to set as a string.
     */
    @SuppressWarnings("unused")
    public void setUsername(String username) {
        this.username = username;
    }
}
